name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Banjo
      run: Invoke-WebRequest https://raw.githubusercontent.com/Chnoblouch/banjo-releases/main/getbanjo.py | Select-Object -Expand Content | python

    - name: Add Banjo to Path
      run: echo "$ENV:USERPROFILE\.banjo\bin" | Out-File -FilePath $ENV:GITHUB_PATH -Encoding utf8 -Append

    - name: Build OpenXR Runtime
      working-directory: "${{ github.workspace }}/openxr_runtime"
      run: banjo build
